import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    'ip-whitelist',
    'sandbox-guide',
    {
      type: 'category',
      label: 'Wallets',
      items: [
        'wallets/index',
        'wallets/list',
        'wallets/details',
      ],
    },
    'withdrawal',
    {
      type: 'category',
      label: 'Withdraw Account Management',
      items: [{type: 'autogenerated', dirName: 'withdraw-account-management'}],
    },
    'webhooks',
    'support',
  ],
};

export default sidebars;
