server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = / {
    try_files /index.html =404;
  }

  location ~ ^(.+)/$ {
    return 301 $1;
  }

  location / {
    try_files $uri.html $uri $uri/index.html =404;
  }
}
